=== ArthurMorganRoadThe1899/LM_SpookyMonth/XML_DTD/3_PrácticaRepositorioSW/repositorio.dtd
<!ELEMENT repositorios (repositorio*)>
        <!ELEMENT repositorio (nombre, categoria, software_list, compañia?)>
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT categoria (#PCDATA)>
        <!ELEMENT software_list (file*)>
        <!ELEMENT file (nombre, etiqueta?, tipo, puntuacion?, size, checksum, fecha_subida, desarrolladores)>
        <!ATTLIST file identificador ID #REQUIRED>
        <!ELEMENT etiqueta (#PCDATA)>
        <!ELEMENT tipo EMPTY>
        <!ATTLIST tipo cual (free | comercial) "free">
        <!ELEMENT puntuacion EMPTY>
        <!ATTLIST puntuacion high (0|1|2|3|4|5) "0">
        <!ELEMENT size (#PCDATA)>
        <!ELEMENT checksum EMPTY>
        <!ATTLIST checksum is (Y | N) "N">
        <!ELEMENT fecha_subida (#PCDATA)>
        <!ELEMENT desarrolladores (desarrollador*)>
        <!ELEMENT desarrollador (nombre, apellido, web_personal?, ocupacion)>
        <!ATTLIST desarrollador id ID #REQUIRED> <!--Lo pongo así, aunque pondría una sección aparte para cada desarrollador, y aquí haría un IDREF-->
        <!ELEMENT apellido (#PCDATA)>
        <!ELEMENT web_personal (#PCDATA)>
        <!ELEMENT ocupacion EMPTY>
        <!ATTLIST ocupacion cual (freelancer | interno) "interno">
        <!ELEMENT compañia (nombre, email, web)>
        <!ELEMENT email (#PCDATA)>
        <!ELEMENT web (#PCDATA)>

=== ArthurMorganRoadThe1899/LM_SpookyMonth/3_PrácticaRepositorioSW/repositorio.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE repositorios SYSTEM "repositorio.dtd">
<repositorios>
    <repositorio>
        <nombre>TareasJava</nombre>
        <categoria>Programacion</categoria>

        <software_list>
            <file identificador="F111">
                <nombre>B_JAA1.java</nombre>
                <etiqueta>Primer archivo</etiqueta>
                <tipo cual="free"/>
                <size>120MB</size>
                <checksum is="Y"/>
                <fecha_subida>24/10/2023</fecha_subida>

                <desarrolladores>
                    <desarrollador id="D6">
                        <nombre>Jose</nombre>
                        <apellido>Alba</apellido>
                        <ocupacion cual="interno"/>
                    </desarrollador>
                </desarrolladores>
            </file>

            <file identificador="F112">
                <nombre>calculadora.java</nombre>
                <tipo cual="free"/>
                <size>100MB</size>
                <checksum is="Y"/>
                <fecha_subida>31/10/2023</fecha_subida>

                <desarrolladores>
                <desarrollador id="D7">
                    <nombre>Jes√∫s</nombre>
                    <apellido>Cereceda</apellido>
                    <ocupacion cual="freelancer"/>
                </desarrollador>
                </desarrolladores>
            </file>
        </software_list>
    </repositorio>
</repositorios>
