<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE ficha [
        <!ELEMENT ficha (datos_emisor, datos_cliente, detalle_factura)?>
        <!ELEMENT datos_emisor EMPTY>
        <!ATTLIST datos_emisor CIF CDATA #REQUIRED>
        <!ATTLIST datos_emisor nombre CDATA #REQUIRED>
        <!ATTLIST datos_emisor teléfono CDATA #REQUIRED>
        <!ELEMENT datos_cliente EMPTY>
        <!ATTLIST datos_cliente CIF CDATA #REQUIRED>
        <!ATTLIST datos_cliente nombre CDATA #REQUIRED>
        <!ATTLIST datos_cliente teléfono CDATA #REQUIRED>
        <!ELEMENT detalle_factura (articulo*, importe)>
        <!ATTLIST detalle_factura CIF CDATA #REQUIRED>
        <!ELEMENT articulo (codigo, tipo, descripcion, cantidad, oferta, pvp)*>
        <!ELEMENT codigo EMPTY>
        <!ATTLIST codigo cod CDATA #REQUIRED>
        <!ELEMENT tipo (#PCDATA)>
        <!ELEMENT descripcion (#PCDATA)>
        <!ELEMENT cantidad (#PCDATA)>
        <!ELEMENT oferta (#PCDATA)>
        <!ELEMENT pvp EMPTY>
        <!ATTLIST pvp total CDATA #REQUIRED>
        <!ELEMENT importe EMPTY>
        <!ATTLIST importe total CDATA #REQUIRED>
        ]>

<ficha>
    <datos_emisor CIF="44555666B" nombre="Librería Pérez" teléfono="777888999"/>
    <datos_cliente CIF="33111222A" nombre="Biblioteca Txantrea" teléfono="333999444"/>

    <detalle_factura CIF="A44555666B">
        <articulo>
            <codigo cod="AW7"/>
            <tipo>Libro</tipo>
            <descripcion>Analítica Web 2.0</descripcion>
            <cantidad>1</cantidad>
            <oferta>SI</oferta>
            <pvp total="25"/>
        </articulo>

        <articulo>
            <codigo cod="CP5"/>
            <tipo>DVD</tipo>
            <descripcion>Curso de HTML</descripcion>
            <cantidad>2</cantidad>
            <oferta>NO</oferta>
            <pvp total="30"/>
        </articulo>
        
        <importe total="85"/>
    </detalle_factura>
</ficha>

<!--Hecho por Jose Alba Arrufat-->