=== ArthurMorganRoadThe1899/LM_SpookyMonth/4_Blog/blog.dtd
<!ELEMENT blogs (blog*)>
        <!ELEMENT blog (titulo, fecha_pub, hora_pub, noticias, puntuacion)>
        <!ATTLIST blog categoria (posting|memes|animales|programacion|special_event|breaking_news|anime) "posting">
        <!ELEMENT titulo (#PCDATA)>
        <!ELEMENT fecha_pub EMPTY>
        <!ATTLIST fecha_pub data CDATA #REQUIRED>
        <!ELEMENT hora_pub EMPTY>
        <!ATTLIST hora_pub hour CDATA #REQUIRED>
        <!ELEMENT noticias (noticia*)>
        <!ELEMENT noticia (titulo, fecha_pub, descripcion, comentarios*)>
        <!ELEMENT descripcion (#PCDATA)>
        <!ELEMENT comentarios (comentario*)>
        <!ELEMENT comentario (contenido, fecha_pub, hora_pub, usuario, imagen?)>
        <!ELEMENT contenido (#PCDATA)>
        <!ELEMENT usuario ANY>
        <!ATTLIST usuario type (anoymous) #IMPLIED>
        <!ELEMENT imagen EMPTY>
        <!ATTLIST imagen URL CDATA #REQUIRED>
        <!ELEMENT puntuacion EMPTY>
        <!ATTLIST puntuacion rate (0|1|2|3) "0">

=== ArthurMorganRoadThe1899/LM_SpookyMonth/XML_DTD/4_Blog/blog.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE blogs SYSTEM "blog.dtd">

<blogs>
    <blog categoria="breaking_news">
        <titulo>Ãšltimas en Caldera, Chile</titulo>
        <fecha_pub data="11/11/2011"/>
        <hora_pub hour="11:12"/>

        <noticias>

            <noticia>
                <titulo>Criminal en la calle</titulo>
                <fecha_pub data="11/12/2016"/>
                <descripcion>Por Chile se ha escapado un peligroso criminal, tengan cuidado a la hora de salir a la calles en Caldera</descripcion>

                <comentarios>
                    <comentario>
                        <contenido>oojala atrapen a ese loco, ya se ha cargado a mucha gente, entre ellos mi tio ðŸ˜”</contenido>
                        <fecha_pub data="11/12/2013"/>
                        <hora_pub hour="13:23"/>
                        <usuario>GeronimoSteel_TOON</usuario>
                    </comentario>

                    <comentario>
                        <contenido>Joer, otra vez</contenido>
                        <fecha_pub data="11/12/2013"/>
                        <hora_pub hour="14:45"/>
                        <usuario type="anoymous"/>
                    </comentario>
                </comentarios>
            </noticia>
        </noticias>
        <puntuacion rate="2"/>
    </blog>
    
    <blog categoria="anime">
        <titulo>GeÃ°klofa KlÃºbburinn</titulo>
        <fecha_pub data="12/9/2020"/>
        <hora_pub hour="21:23"/>
        <noticias>
            <noticia>
                <titulo>Autor de SNK y el netorare</titulo>
                <fecha_pub data="2/11/2023"/>
                <descripcion>El autor de SNK es fan del subgenero de anime para adultos netorare</descripcion>

                <comentarios>
                    <comentario>
                        <contenido>fan del netorare (NTR) XD</contenido>
                        <fecha_pub data="2/11/2023"/>
                        <hora_pub hour="19:51"/>
                        <usuario>ravvava_shamurai</usuario>
                    </comentario>
                    <comentario>
                        <contenido>Yase noto enel manga</contenido>
                        <fecha_pub data="2/11/2023"/>
                        <hora_pub hour="20:11"/>
                        <usuario>carlitosbraian777</usuario>
                    </comentario>
                </comentarios>
            </noticia>
        </noticias>
        <puntuacion/>
    </blog>
</blogs>
